### ISSUE TITLE
Features and Interaction

### ISSUE THREAD

**Issue by kstseng** [andland/libFMexe#12] opened 2016-07-12 15:49 UTC
Hi, Andrew, 

Can you give an example of adding feature and 2 way interaction by libFMexe?
I saw the parameter explanation, but I still not sure how to implement.

Thanks.

**Comment by andland** [comment] 2016-07-22 16:52
Say you have a data.frame called `df_train` with columns `x1`, `x2`, and `y`. libFM makes the most sense when  `x1` and `x2` are categorical variables with lots of levels. Say `y` is continuous, so we are doing regression. Finally, libFM requires you to input your testing data at training time, so lets say you also have a data.frame that you want to make predictions on called `df_test`.

The following code will just include the main effects of `x1` and `x2` because `dim = 0`. 

```
predFM = libFM(df_train, df_test, y ~ x1 + x2, task = "r", dim = 0)
```

To do a two-way interaction of all of the levels of `x1` and `x2`, we just need to increase the `dim` value above 0. The higher it is, the better it will fit your training data, but not necessarily your testing data. For example, setting `dim = 10` will approximate each level of `x1` and `x2` with a 10-dimensional vector. The interaction of level `i` of `x1` and level `j` of `x2` will be the inner product the `i`th vector for `x1` and the `j`th vector for `x2`. 

```
predFM = libFM(df_train, df_test, y ~ x1 + x2, task = "r", dim = 10)
```

There is not too much flexibility in libFM, which means that if you have more than two covariates, all two-way interactions between every variable will be included when `dim` is above 0.

`dim` is a tuning parameter which you can assess with the `cv_libFM` function.

```
mses = cv_libFM(df_train, df_test, y ~ x1 + x2, task = "r", dims = seq(0, 20, by = 5))
```

**Closed as completed by andland** 2016-07-22 16:52 UTC
